setInterval(function(){
	odometer6digit.innerHTML = MathyJS.random(999999,100000)
},5000)
setInterval(function(){
	odometer5digit.innerHTML = MathyJS.random(99999,10000)
},5000)
setInterval(function(){
	odometer4digit.innerHTML = MathyJS.random(9999,1000)
},5000)
setInterval(function(){
	odometer3digit.innerHTML = MathyJS.random(999,100)
},5000)
setInterval(function(){
	odometer2digit.innerHTML = MathyJS.random(99,10)
},5000)
setInterval(function(){
	odometer1digit.innerHTML = MathyJS.random(9,1)
},5000)
